# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

QT			+=	core_gui \
				multimedia
TEMPLATE	=	app
TARGET		=	LearningQt
DESTDIR		=	../x64/Debug
CONFIG		+=	debug
LIBS		+=	-L"."
DEPENDPATH	+=	.
MOC_DIR		+=	.
OBJECTS_DIR	+=	debug
UI_DIR		+=	.
RCC_DIR		+=	.
include(LearningQt.pri)
